### ISSUE TITLE
Remove usage of db.pool

### ISSUE THREAD

**Issue by pyphilia** [graasp/graasp-plugin-chatbox#46]
https://github.com/graasp/graasp-plugin-chatbox/blob/132e4d82129a9ec7989959b78fec641352211248/src/service-api.ts#L270

**Comment by dialexo** [comment]
This usage of `db.pool` should not be removed, as it is only used when clients are requesting to subscribe to the corresponding websocket channels. However some `setTaskPre/PostHookHandler` do not use the provided `handler` which will be addressed in #47.

Maybe the websockets plugin should begin a transaction at its own plugin level, see https://github.com/graasp/graasp-websockets/issues/33
